




.build/uno/src/payload_atmega328p.cpp : src/payload_atmega328p.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/payload_atmega328p.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/payload_atmega328p.cpp
	@true

